default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hospital_development

test:
  <<: *default
  database: hospital_test

production:
  <<: *default
  database: hospital_production
  username: hospital
  password: <%= ENV["HOSPITAL_DATABASE_PASSWORD"] %>
